"""empty message

Revision ID: 6307ea03b479
Revises: 
Create Date: 2024-10-17 13:01:56.789312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6307ea03b479'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=80), nullable=False),
    sa.Column('course_description', sa.String(length=80), nullable=False),
    sa.Column('course_image', sa.String(length=80), nullable=False),
    sa.Column('course_author', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_author'),
    sa.UniqueConstraint('course_description'),
    sa.UniqueConstraint('course_image'),
    sa.UniqueConstraint('course_name')
    )
    op.create_table('instructor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ins_fname', sa.String(length=80), nullable=False),
    sa.Column('ins_lname', sa.String(length=80), nullable=False),
    sa.Column('ins_email', sa.String(length=80), nullable=False),
    sa.Column('ins_password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ins_email'),
    sa.UniqueConstraint('ins_fname'),
    sa.UniqueConstraint('ins_lname'),
    sa.UniqueConstraint('ins_password')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('st_fname', sa.String(length=80), nullable=False),
    sa.Column('st_lname', sa.String(length=80), nullable=False),
    sa.Column('st_email', sa.String(length=80), nullable=False),
    sa.Column('st_password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('st_email'),
    sa.UniqueConstraint('st_fname'),
    sa.UniqueConstraint('st_lname'),
    sa.UniqueConstraint('st_password')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    op.drop_table('instructor')
    op.drop_table('course')
    # ### end Alembic commands ###
