"""empty message

Revision ID: f87a88954722
Revises: 6307ea03b479
Create Date: 2024-10-17 14:41:25.957779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f87a88954722'
down_revision = '6307ea03b479'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=80), nullable=False),
    sa.Column('course_description', sa.String(length=80), nullable=False),
    sa.Column('course_image', sa.String(length=80), nullable=False),
    sa.Column('course_author', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_author'),
    sa.UniqueConstraint('course_description'),
    sa.UniqueConstraint('course_image'),
    sa.UniqueConstraint('course_name')
    )
    op.create_table('instructors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ins_fname', sa.String(length=80), nullable=False),
    sa.Column('ins_lname', sa.String(length=80), nullable=False),
    sa.Column('ins_email', sa.String(length=80), nullable=False),
    sa.Column('ins_password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ins_email'),
    sa.UniqueConstraint('ins_fname'),
    sa.UniqueConstraint('ins_lname'),
    sa.UniqueConstraint('ins_password')
    )
    op.drop_table('course')
    op.drop_table('instructor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instructor',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ins_fname', sa.VARCHAR(length=80), nullable=False),
    sa.Column('ins_lname', sa.VARCHAR(length=80), nullable=False),
    sa.Column('ins_email', sa.VARCHAR(length=80), nullable=False),
    sa.Column('ins_password', sa.VARCHAR(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ins_email'),
    sa.UniqueConstraint('ins_fname'),
    sa.UniqueConstraint('ins_lname'),
    sa.UniqueConstraint('ins_password')
    )
    op.create_table('course',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('course_name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('course_description', sa.VARCHAR(length=80), nullable=False),
    sa.Column('course_image', sa.VARCHAR(length=80), nullable=False),
    sa.Column('course_author', sa.VARCHAR(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_author'),
    sa.UniqueConstraint('course_description'),
    sa.UniqueConstraint('course_image'),
    sa.UniqueConstraint('course_name')
    )
    op.drop_table('instructors')
    op.drop_table('courses')
    # ### end Alembic commands ###
